### ISSUE TITLE
Profile and toot backgrounds

### ISSUE THREAD

**Issue by DeadSuperHero** [tootsuite/mastodon#1040]
This seems like it could be a really easy fix, and I think it might actually make for a nice visual enhancement.

As a small concession for personalization, it would be nice if the background on user profiles and individual toots matched with the header image. So, if I navigate to my user page, I can see a blurred background that matches it. 

<img width="1054" alt="sean_tilley_-_social_nasqueron" src="https://cloud.githubusercontent.com/assets/401560/24745335/324214be-1a6a-11e7-83f9-7eb42f38fc94.png">

This is incidentally not that hard to create with CSS, and I think it can be accomplished with a pretty basic change to some templates. Rather than being a custom image, backgrounds can be created automatically from uploading a header picture.

The only caveat I can think of is that a basic fallback image might be necessray for new users who haven't set an image yet.

**Comment by mkody** [comment]
This looks really nice, [I've tried it on my instance](https://im-in.space/@kdy).

I added those two lines to `app/views/accounts/show.html.haml` above the `.h-feed`
```
.bg-header
  .bg-header-img{ style: "background-image: url(#{@account.header.url( :original)})" }
```

And then some scss (in `app/assets/stylesheets/accounts.scss`)
```scss
.bg-header {
    filter: blur(8px);
    height: 100%;
    left: 0;
    position: fixed;
    top: 0;
    width: 100%;
    z-index: -1;

    .bg-header-img {
        background-size: cover;
        background-position: center;
        height: calc(100% + 30px);
        margin: -15px;
        width: calc(100% + 30px);
    }
}
```

The negative margins and the `calc(100% + 30px)` are to hide the black spots made by the blur effect.

When a user doesn't have a header image, we can see the default Mastodon background [(example)](https://im-in.space/@curv).  
Does that look good enough?
