### ISSUE TITLE
Very long hashtag protrude in the report dialog

### ISSUE THREAD

**Issue by miyacorata** [tootsuite/mastodon#12942]
### Expected behaviour
![image](https://user-images.githubusercontent.com/12165058/73083281-405ab580-3f0e-11ea-9fa5-a2ad9ccb0219.png)

note : insert CSS via DevTools.
```css
div.status-check-box__status > div > p > a {
    word-break: break-word;
}
```

### Actual behaviour
![image](https://user-images.githubusercontent.com/12165058/73083187-16a18e80-3f0e-11ea-8a78-7b338b872fba.png)
The checkbox disappeared because it was pushed out by the hashtag.

### Steps to reproduce the problem
1. Open report dialog of toot contain very long hashtag

### Specifications
mastodon : Ver3.0.1

Chrome : 79.0.3945.130 (Official Build, 64bit, cohort: Stable)
Firefox : 72.0.2 (Stable, 64bit)
