### ISSUE TITLE
Colourblind accessability on icons

### ISSUE THREAD

**Issue by shleeable** [tootsuite/mastodon#14390]
<img width="78" alt="image" src="https://user-images.githubusercontent.com/17537000/88449077-9f29c900-ce76-11ea-8d85-f193da09952b.png">

### Expected behaviour

Being able to see which toots I've previously boosted.

### Actual behaviour

my stupid eyes can't really tell the difference from the gray and the bubble gum blue.

### Steps to reproduce the problem

Have my eyes.

**Comment by shleeable** [comment]
![image](https://user-images.githubusercontent.com/17537000/88449190-76ee9a00-ce77-11ea-8f5e-54c76dea45e4.png)

Me trying to figure out if it's grey or blue green.

**Comment by Sasha-Sorokin** [comment]
> **Steps to reproduce the problem**
> Be colorblind.

[Ight Imma head out](https://i.kym-cdn.com/entries/icons/mobile/000/030/967/spongebob.jpg)

Well, jokes aside, I've been playing around with colorblind simulation long time ago and noticed that some of the buttons were really hard to see, turns out yes, they are. Do you have any ideas how this can be improved?

Do you think adding lines gradient is an improvement? If so, this could be colorblind friendly option in settings, technically this could work by adding .colorblind-mode to body class and then relating to this class in styles.

<details><summary>SASS example</summary>

```scss
@mixin colorblind-stripes($color, $rotation: 125deg, $property: background) {
    $secondary-color: lighten($color, 35%);
    #{$property}: repeating-linear-gradient($rotation, $color, $color 6px, $secondary-color 9px, $secondary-color 5px);
}

@mixin colorblind-stripes-clip($color, $rotation: 125deg) {
    // Order matters! If we're passing background after clipping, it won't work.
    @include colorblind-stripes($color, $rotation, background);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}

.star-icon.active {
  $active-color: #ca8f04;
  color: $active-color;
  
  .colorblind-mode & {
    @include colorblind-stripes-clip($active-color);
  }
}

$boost-icon-url: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='22' height='209'><path d='M4.97 3.16c-.1.03-.17.1-.22.18L.8 8.24c-.2.3.03.78.4.8H3.6v2.68c0 4.26-.55 3.62 3.66 3.62h7.66l-2.3-2.84c-.03-.02-.03-.04-.05-.06H7.27c-.44 0-.72-.3-.72-.72v-2.7h2.5c.37.03.63-.48.4-.77L5.5 3.35c-.12-.17-.34-.25-.53-.2zm12.16.43c-.55-.02-1.32.02-2.4.02H7.1l2.32 2.85.03.06h5.25c.42 0 .72.28.72.72v2.7h-2.5c-.36.02-.56.54-.3.8l3.92 4.9c.18.25.6.25.78 0l3.94-4.9c.26-.28 0-.83-.37-.8H18.4v-2.7c0-3.15.4-3.62-1.25-3.66z' fill='%238D9AC2' stroke-width='0'/><path d='M7.78 19.66c-.24.02-.44.25-.44.5v2.46h-.06c-1.08 0-1.86-.03-2.4-.03-1.64 0-1.25.43-1.25 3.65v4.47c0 4.26-.56 3.62 3.65 3.62H8.5l-1.3-1.06c-.1-.08-.18-.2-.2-.3-.02-.17.06-.35.2-.45l1.33-1.1H7.28c-.44 0-.72-.3-.72-.7v-4.48c0-.44.28-.72.72-.72h.06v2.5c0 .38.54.63.82.38l4.9-3.93c.25-.18.25-.6 0-.78l-4.9-3.92c-.1-.1-.24-.14-.38-.12zm9.34 2.93c-.54-.02-1.3.02-2.4.02h-1.25l1.3 1.07c.1.07.18.2.2.33.02.16-.06.3-.2.4l-1.33 1.1h1.28c.42 0 .72.28.72.72v4.47c0 .42-.3.72-.72.72h-.1v-2.47c0-.3-.3-.53-.6-.47-.07 0-.14.05-.2.1l-4.9 3.93c-.26.18-.26.6 0 .78l4.9 3.92c.27.25.82 0 .8-.38v-2.5h.1c4.27 0 3.65.67 3.65-3.62v-4.47c0-3.15.4-3.62-1.25-3.66zM10.34 38.66c-.24.02-.44.25-.43.5v2.47H7.3c-1.08 0-1.86-.04-2.4-.04-1.64 0-1.25.43-1.25 3.65v4.47c0 3.66-.23 3.7 2.34 3.66l-1.34-1.1c-.1-.08-.18-.2-.2-.3 0-.17.07-.35.2-.45l1.96-1.6c-.03-.06-.04-.13-.04-.2v-4.48c0-.44.28-.72.72-.72H9.9v2.5c0 .36.5.6.8.38l4.93-3.93c.24-.18.24-.6 0-.78l-4.94-3.92c-.1-.08-.23-.13-.36-.12zm5.63 2.93l1.34 1.1c.1.07.18.2.2.33.02.16-.03.3-.16.4l-1.96 1.6c.02.07.06.13.06.22v4.47c0 .42-.3.72-.72.72h-2.66v-2.47c0-.3-.3-.53-.6-.47-.06.02-.12.05-.18.1l-4.94 3.93c-.24.18-.24.6 0 .78l4.94 3.92c.28.22.78-.02.78-.38v-2.5h2.66c4.27 0 3.65.67 3.65-3.62v-4.47c0-3.66.34-3.7-2.4-3.66zM13.06 57.66c-.23.03-.4.26-.4.5v2.47H7.28c-1.08 0-1.86-.04-2.4-.04-1.64 0-1.25.43-1.25 3.65v4.87l2.93-2.37v-2.5c0-.44.28-.72.72-.72h5.38v2.5c0 .36.5.6.78.38l4.94-3.93c.24-.18.24-.6 0-.78l-4.94-3.92c-.1-.1-.24-.14-.38-.12zm5.3 6.15l-2.92 2.4v2.52c0 .42-.3.72-.72.72h-5.4v-2.47c0-.3-.32-.53-.6-.47-.07.02-.13.05-.2.1L3.6 70.52c-.25.18-.25.6 0 .78l4.93 3.92c.28.22.78-.02.78-.38v-2.5h5.42c4.27 0 3.65.67 3.65-3.62v-4.47-.44zM19.25 78.8c-.1.03-.2.1-.28.17l-.9.9c-.44-.3-1.36-.25-3.35-.25H7.28c-1.08 0-1.86-.03-2.4-.03-1.64 0-1.25.43-1.25 3.65v.7l2.93.3v-1c0-.44.28-.72.72-.72h7.44c.2 0 .37.08.5.2l-1.8 1.8c-.25.26-.08.76.27.8l6.27.7c.28.03.56-.25.53-.53l-.7-6.25c0-.27-.3-.48-.55-.44zm-17.2 6.1c-.2.07-.36.3-.33.54l.7 6.25c.02.36.58.55.83.27l.8-.8c.02 0 .04-.02.04 0 .46.24 1.37.17 3.18.17h7.44c4.27 0 3.65.67 3.65-3.62v-.75l-2.93-.3v1.05c0 .42-.3.72-.72.72H7.28c-.15 0-.3-.03-.4-.1L8.8 86.4c.3-.24.1-.8-.27-.84l-6.28-.65h-.2zM4.88 98.6c-1.33 0-1.34.48-1.3 2.3l1.14-1.37c.08-.1.22-.17.34-.2.16 0 .34.08.44.2l1.66 2.03c.04 0 .07-.03.12-.03h7.44c.34 0 .57.2.65.5h-2.43c-.34.05-.53.52-.3.78l3.92 4.95c.18.24.6.24.78 0l3.94-4.94c.22-.27-.02-.76-.37-.77H18.4c.02-3.9.6-3.4-3.66-3.4H7.28c-1.08 0-1.86-.04-2.4-.04zm.15 2.46c-.1.03-.2.1-.28.2l-3.94 4.9c-.2.28.03.77.4.78H3.6c-.02 3.94-.45 3.4 3.66 3.4h7.44c3.65 0 3.74.3 3.7-2.25l-1.1 1.34c-.1.1-.2.17-.32.2-.16 0-.34-.08-.44-.2l-1.65-2.03c-.06.02-.1.04-.18.04H7.28c-.35 0-.57-.2-.66-.5h2.44c.37 0 .63-.5.4-.78l-3.96-4.9c-.1-.15-.3-.23-.47-.2zM4.88 117.6c-1.16 0-1.3.3-1.3 1.56l1.14-1.38c.08-.1.22-.14.34-.16.16 0 .34.04.44.16l2.22 2.75h7c.42 0 .72.28.72.72v.53h-2.6c-.3.1-.43.54-.2.78l3.92 4.9c.18.25.6.25.78 0l3.94-4.9c.22-.28-.02-.77-.37-.78H18.4v-.53c0-4.2.72-3.63-3.66-3.63H7.28c-1.08 0-1.86-.03-2.4-.03zm.1 1.74c-.1.03-.17.1-.23.16L.8 124.44c-.2.28.03.77.4.78H3.6v.5c0 4.26-.55 3.62 3.66 3.62h7.44c1.03 0 1.74.02 2.28 0-.16.02-.34-.03-.44-.15l-2.22-2.76H7.28c-.44 0-.72-.3-.72-.72v-.5h2.5c.37.02.63-.5.4-.78L5.5 119.5c-.12-.15-.34-.22-.53-.16zm12.02 10c1.2-.02 1.4-.25 1.4-1.53l-1.1 1.36c-.07.1-.17.17-.3.18zM5.94 136.6l2.37 2.93h6.42c.42 0 .72.28.72.72v1.25h-2.6c-.3.1-.43.54-.2.78l3.92 4.9c.18.25.6.25.78 0l3.94-4.9c.22-.28-.02-.77-.37-.78H18.4v-1.25c0-4.2.72-3.63-3.66-3.63H7.28c-.6 0-.92-.02-1.34-.03zm-1.72.06c-.4.08-.54.3-.6.75l.6-.74zm.84.93c-.12 0-.24.08-.3.18l-3.95 4.9c-.24.3 0 .83.4.82H3.6v1.22c0 4.26-.55 3.62 3.66 3.62h7.44c.63 0 .97.02 1.4.03l-2.37-2.93H7.28c-.44 0-.72-.3-.72-.72v-1.22h2.5c.4.04.67-.53.4-.8l-3.96-4.92c-.1-.13-.27-.2-.44-.2zm13.28 10.03l-.56.7c.36-.07.5-.3.56-.7zM17.13 155.6c-.55-.02-1.32.03-2.4.03h-8.2l2.38 2.9h5.82c.42 0 .72.28.72.72v1.97H12.9c-.32.06-.48.52-.28.78l3.94 4.94c.2.23.6.22.78-.03l3.94-4.9c.22-.28-.02-.77-.37-.78H18.4v-1.97c0-3.15.4-3.62-1.25-3.66zm-12.1.28c-.1.02-.2.1-.28.18l-3.94 4.9c-.2.3.03.78.4.8H3.6v1.96c0 4.26-.55 3.62 3.66 3.62h8.24l-2.36-2.9H7.28c-.44 0-.72-.3-.72-.72v-1.97h2.5c.37.02.63-.5.4-.78l-3.96-4.9c-.1-.15-.3-.22-.47-.2zM5.13 174.5c-.15 0-.3.07-.38.2L.8 179.6c-.24.27 0 .82.4.8H3.6v2.32c0 4.26-.55 3.62 3.66 3.62h7.94l-2.35-2.9h-5.6c-.43 0-.7-.3-.7-.72v-2.3h2.5c.38.03.66-.54.4-.83l-3.97-4.9c-.1-.13-.23-.2-.38-.2zm12 .1c-.55-.02-1.32.03-2.4.03H6.83l2.35 2.9h5.52c.42 0 .72.28.72.72v2.34h-2.6c-.3.1-.43.53-.2.78l3.92 4.9c.18.24.6.24.78 0l3.94-4.9c.22-.3-.02-.78-.37-.8H18.4v-2.33c0-3.15.4-3.62-1.25-3.66zM4.97 193.16c-.1.03-.17.1-.22.18l-3.94 4.9c-.2.3.03.78.4.8H3.6v2.68c0 4.26-.55 3.62 3.66 3.62h7.66l-2.3-2.84c-.03-.02-.03-.04-.05-.06H7.27c-.44 0-.72-.3-.72-.72v-2.7h2.5c.37.03.63-.48.4-.77l-3.96-4.9c-.12-.17-.34-.25-.53-.2zm12.16.43c-.55-.02-1.32.03-2.4.03H7.1l2.32 2.84.03.06h5.25c.42 0 .72.28.72.72v2.7h-2.5c-.36.02-.56.54-.3.8l3.92 4.9c.18.25.6.25.78 0l3.94-4.9c.26-.28 0-.83-.37-.8H18.4v-2.7c0-3.15.4-3.62-1.25-3.66z' fill='%232B90D9' stroke-width='0'/></svg>");

.boost-button {
    $active-color: #2b90d9;
    
    // Allows us to align before mask correctly.
    // The ::before pseudo is a bad hack, by the way.
    position: relative;
    
    &.active { color: $active-color };
    
    .colorblind-mode &.active {
        &::before {
           content: "";
           width: 22px;
           height: 19px;
           top: 2px;
           position: absolute;
           vertical-align: middle;
           @include colorblind-stripes($active-color, 125deg, background);
           mask: {
               image: $boost-icon-url;
               position: 0 100%;
           }
        }
    }
}
```

</details>

| Inactive | Active |
|:---:|:---:|
| ![Inactive buttons example, no changes](https://user-images.githubusercontent.com/10401817/88462595-b8626200-ced6-11ea-873e-b3c44f9e2952.png) | ![Active buttons example, buttons now have gradient over them](https://user-images.githubusercontent.com/10401817/88462555-6b7e8b80-ced6-11ea-9ca8-3c2577971c0d.png) |


*btw I'm bad at gradients, but I think it could be easily changed to be more noticeable, but still looking good.*

**Comment by SuperSandro2000** [comment]
This could be a setting which would allow us to use any color that fits well with colorblind people.

**Comment by Sasha-Sorokin** [comment]
@SuperSandro2000 this will be hard to implement and also falls into theming category…

**Comment by Gargron** [comment]
It might've been easier to add if there was *no* theming...

**Comment by noellabo** [comment]
![inverted icon](https://user-images.githubusercontent.com/28195220/88477891-b5bb4780-cf7e-11ea-8be1-ab18971d8917.png)
The inverted icon will probably be easily identifiable.

**Comment by shleeable** [comment]
I do like the idea of "active" icons having some kind of flare.... Like the line thru star

**Comment by Sasha-Sorokin** [comment]
@shleeable outlined [inactive] icons would be ideal! ...if only Font Awesome supported them. Newer versions of FA [support them](https://fontawesome.com/icons?d=gallery&s=regular), but only for paid subscribers ([incompatible with open source](https://fontawesome.com/plans#faq-where-use)) and they also don't look as clear as FA4 we use ([can be seen here](https://mastodon.social/@sasha_sorokin/103468041333070514)), there are also major inconsistencies between outlined and filled style [for some icons](https://fontawesome.com/icons/home?style=regular) -_-

I think we need general icons refresh on Mastodon, but we have no designers to do it, probably have to hire somebody. I tried searching for fresh open source icon packs, but unfortunately most of them don't have icons we need, like that one… `retweet` :(

What about @noellabo's idea, is it more clear? It would be also much easier to implement for the time being, because my idea uses CSS masking which requires to kinda ‘override’ color of the icon, so you have to pass color of each icon to the function (surely, this can be optimized), but for @noellabo's concept it will be as simple as invert color of IconButton component if it's in active state, maybe colors can be passed as CSS variables.

<details><summary>SASS example</summary>

```scss
// TODO: check conflicts with .inverted style
// FIXME: use $variables for default colors, so dark/light theming works correctly
.icon-button.active {
  color: var(--iconbutton-active-color, #2b90d9);
  background: var(--iconbutton-active-bg, transparent);

  .colorblind-mode & {
    background: var(--iconbutton-active-color, #2b90d9);
    color: var(--iconbutton-active-bg, white);
  }
}

.icon-button.star-icon {
  --iconbutton-active-color: #ca8f04;
}
```
</details>
