### ISSUE TITLE
Search, @mentions and #hashtags return HTTP 500

### ISSUE THREAD

**Issue by f0086** [tootsuite/mastodon#14558]
### Expected behaviour

* After typing something in the searchbox and hitting enter, the results should appear
* @mentions should be autocompleted
* #hashtags should be autocompleted

### Actual behaviour

After the upgrade to v3.2.0, a popup with "500 Internal Server Error" appears in the UI after typing @mentions or #hashtags. The server console reveals the following error message:

`web_1        | [098869e5-51d1-4ad4-850f-2783324ba916] Elasticsearch::Transport::Transport::Errors::BadRequest ([400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/accounts/account/_search] contains unrecognized parameter: [rest_total_hits_as_int]"}],"type":"illegal_argument_exception","reason":"request [/accounts/account/_search] contains unrecognized parameter: [rest_total_hits_as_int]"},"status":400}):`

Elasticsearch is starting up fine in version 6.0.8, so it can't be an incompatibility issue with 7.0.0. 

### Steps to reproduce the problem

1. Open the web UI
2. Start a new toot and type @asdf
3. See the 500 error

### Specifications

We start mastodon with the following docker-compose.yaml:

```
version: '3'
services:

  db:
    restart: always
    image: postgres:10.4-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - ./postgres:/var/lib/postgresql/data
        # to mount the working dir to access sql dumps
        #- ./:/backup

  redis:
    restart: always
    image: redis:4.0-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data

  es:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data

  web:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - external_network
      - internal_network
    healthcheck:
            test: ["CMD-SHELL", "wget -q --spider https://social.okoyono.de/api/v1/instance || exit 1"]
    ports:
      - "127.0.0.1:3002:3000"
    depends_on:
      - db
      - redis
      - es
    volumes:
      - ./public/system:/mastodon/public/system

  streaming:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    command: yarn start
    networks:
      - external_network
      - internal_network
    healthcheck:
            test: ["CMD-SHELL", "wget -q --spider https://social.okoyono.de/api/v1/streaming/health || exit 1"]
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system

networks:
  external_network:
  internal_network:
    internal: true
```
