### ISSUE TITLE
Use Matrix for messaging and voice/video chat

### ISSUE THREAD

**Issue by trymeouteh** [tootsuite/mastodon#14576]
Please add the Matrix protocol to Mastodon to allow for end-to-end encrypted messaging, voice and video chats. Mastodon instances can include a Matrix server within them which will allow all users on the instance to communicate with others on their instance and other instances. For example...

@bob@mastodon.social will automatically have the matrix username of @bob:mastodon.social

And users could use Matrix clients to communicate with others using their Mastodon Matrix account.

I would suggest having voice and video calls being optional to the user and the admin of the instance.

**Comment by ThibG** [comment]
From what I understand of this issue, you are suggesting some way to have a Synapse (or other Matrix implementation) instance run besides Mastodon, and have a way for them to share user credentials. I don't know if some custom integration with Synapse (or another Matrix implementation) would make much sense here, why not use the existing, more generic mechanisms such as the LDAP integration?

Another approach would be to have Mastodon act as a Matrix server itself. I'm afraid that would be too involved (and again, Rails is probably not the best suited piece of technology to do that), but I have to admit I am not quite sure how much work that would actually involve. It's also probably not going to be super useful if the Mastodon Web UI doesn't provide some basic Matrix client functionality.

Also, it must be noted that some E2EE support is in the works. The cryptographic protocol is pretty much the same as Matrix's for one-on-one communications, with the addition of message franking. Group chat specific functionality is out of scope for now. It's still in an early stage, though.

**Comment by mpfaff** [comment]
Matrix is complex enough to be a separate service IMO.

**Comment by OmmyZhang** [comment]
I think Synapse with your Mastodon instance as the SSO provider is what you want. That's exactly what I do currently. (You can see chat.closed.social as a demo)

But the way, I don't think it's a good idea to put social and IM together..

**Comment by OmmyZhang** [comment]
Here is the key parts in synapse's `homeserver.yaml`, hope it helps :) 
Just change `<your-host>` to the host of your mastodon instance.

```yaml
  # the OIDC issuer. Used to validate tokens and (if discovery is enabled) to
  # discover the provider's endpoints.
  #
  # Required if 'enabled' is true.
  #
  issuer: "https://<your-host>/"

  # oauth2 client id to use.
  #
  # Required if 'enabled' is true.
  #
  #client_id: "provided-by-your-issuer"
  client_id: "<client-id>"

  # oauth2 client secret to use.
  #
  # Required if 'enabled' is true.
  #
  #client_secret: "provided-by-your-issuer"
  client_secret: "<client-secret>"

  # auth method to use when exchanging the token.
  # Valid values are 'client_secret_basic' (default), 'client_secret_post' and
  # 'none'.
  #
  #client_auth_method: client_secret_post

  # list of scopes to request. This should normally include the "openid" scope.
  # Defaults to ["openid"].
  #
  #scopes: ["openid", "profile"]
  scopes: ["read:accounts"]

  # the oauth2 authorization endpoint. Required if provider discovery is disabled.
  #
  #authorization_endpoint: "https://accounts.example.com/oauth2/auth"
  authorization_endpoint: "https://<your-host>/oauth/authorize"

  # the oauth2 token endpoint. Required if provider discovery is disabled.
  #
  #token_endpoint: "https://accounts.example.com/oauth2/token"
  token_endpoint: "https://<your-host>/oauth/token"

  # the OIDC userinfo endpoint. Required if discovery is disabled and the
  # "openid" scope is not requested.
  #
  #userinfo_endpoint: "https://accounts.example.com/userinfo"
  userinfo_endpoint: "https://<your-host>/api/v1/accounts/verify_credentials"

user_mapping_provider:
    # The custom module's class. Uncomment to use a custom module.
    # Default is 'synapse.handlers.oidc_handler.JinjaOidcMappingProvider'.
    #
    # See https://github.com/matrix-org/synapse/blob/master/docs/sso_mapping_providers.md#openid-mapping-providers
    # for information on implementing a custom mapping provider.
    #
    #module: mapping_provider.OidcMappingProvider

    # Custom configuration values for the module. This section will be passed as
    # a Python dictionary to the user mapping provider module's `parse_config`
    # method.
    #
    # The examples below are intended for the default provider: they should be
    # changed if using a custom provider.
    #
    config:
      # name of the claim containing a unique identifier for the user.
      # Defaults to `sub`, which OpenID Connect compliant providers should provide.
      #
      subject_claim: "id"

      # Jinja2 template for the localpart of the MXID.
      #
      # When rendering, this template is given the following variables:
      #   * user: The claims returned by the UserInfo Endpoint and/or in the ID
      #     Token
      #
      # This must be configured if using the default mapping provider.
      #
      localpart_template: "{{ user.username }}"

      # Jinja2 template for the display name to set on first login.
      #
      # If unset, no displayname will be set.
      #
      display_name_template: "{{ user.display_name }}"
```
