### ISSUE TITLE
Docker Install - Can’t setup the database

### ISSUE THREAD

**Issue by Acksop** [tootsuite/mastodon#15300]
Hello,
I attempt to install Mastodon (stable-3.2) in a docker-compose setup,

the command

```
docker-compose run --rm web rails db:migrate

can’t connect to db container !

acksop@besancon25:/home/docker/mastodon - stable-3.2$sudo docker-compose run --rm web rails db:setup
Starting mastodon_redis_1_adf643f04bc0 ... done
Starting db                            ... done
could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?
Couldn't create 'mastodon_production' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?
```

here is the dockerfile.yml

```
version: '3'
services:

  db:
    restart: always
    image: postgres:latest
    shm_size: 256mb
    container_name: db
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    expose:
      - "5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=XXXXX
      - POSTGRES_DB=mastodon_production
      - POSTGRES_USER=mastodon
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    restart: always
    image: redis:6.0-alpine
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ./redis:/data

#  es:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "cluster.name=es-mastodon"
#      - "discovery.type=single-node"
#      - "bootstrap.memory_lock=true"
#    networks:
#      - internal_network
#    healthcheck:
#      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
#    volumes:
#      - ./elasticsearch:/usr/share/elasticsearch/data
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1

  web:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - db:db
    depends_on:
      - db
      - redis
#      - es
    volumes:
      - ./public/system:/mastodon/public/system

  streaming:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/mastodon/public/system
## Uncomment to enable federation with tor instances along with adding the following ENV variables
## http_proxy=http://privoxy:8118
## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
#  tor:
#    image: sirboops/tor
#    networks:
#      - external_network
#      - internal_network
#
#  privoxy:
#    image: sirboops/privoxy
#    volumes:
#      - ./priv-config:/opt/config
#    networks:
#      - external_network
#      - internal_network

networks:
  external_network:
  internal_network:
    driver: bridge
```

and the lines about in my .env.production

```
# PostgreSQL
# ----------
DB_HOST=127.0.0.1
DB_USER=mastodon
DB_NAME=mastodon_production
DB_PASS=XXXX
DB_PORT=5432
```

I have tested also with

```
# PostgreSQL
# ----------
DB_HOST=db
DB_USER=mastodon
DB_NAME=mastodon_production
DB_PASS=XXXX
DB_PORT=5432
```

I use the [GitHub - tootsuite/mastodon at stable-3.2](https://github.com/tootsuite/mastodon/tree/stable-3.2) to install, but i have make some modification on dockerfile.yml
This should work, regardless to my previous use of docker …
I don’t understand why the connection doesn’t work on it, this time …

A little help will be very usefull …

if you want you can aswer at [Mastodon Discourse Forum](https://discourse.joinmastodon.org/t/docker-install-cant-setup-the-database/3114)
