### ISSUE TITLE
Ellipsize boost/fav notifications

### ISSUE THREAD

**Issue by chris-martin** [tootsuite/mastodon#1868]
Boosts/favs can take up a lot of space in the notifications column. A quick and easy way to address that is to truncate the content. You don't usually need to see the full content, because you're the one who wrote it - the first line suffices.

![screenshot from 2017-04-15 15-17-06](https://cloud.githubusercontent.com/assets/399718/25066236/a9a7b910-21ee-11e7-947d-fd3c1eb58670.png)

Here's the CSS I applied to get that effect:

```css
.notification-favourite p,
.notification-reblog p {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
    margin: 0;
}

.notification-favourite .status__content p,
.notification-reblog .status__content p {
    display: none;
}

.notification-favourite .status__content p:nth-child(1),
.notification-reblog .status__content p:nth-child(1) {
    display: block;
}
```

I can submit a PR if there's interest.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
