### ISSUE TITLE
404 error is not localized

### ISSUE THREAD

**Issue by unarist** [tootsuite/mastodon#2195]
[`config/locales/*.yml`](https://github.com/tootsuite/mastodon/blob/v1.2.2/config/locales/en.yml#L205) has `errors.404`:

```yaml
  errors:
    '404': The page you were looking for doesn't exist.
    '410': The page you were looking for doesn't exist anymore.
    '422':
      content: Security verification failed. Are you blocking cookies?
      title: Security verification failed
```

and there is a translation for it, e.g. [ja.yml](https://github.com/tootsuite/mastodon/blob/v1.2.2/config/locales/ja.yml#L205):

```yaml
  errors:
    '404': お探しのページは見つかりませんでした。
    '410': お探しのページはもう存在しません。
    '422':
      content: セキュリティ認証に失敗しました。Cookieをブロックしていませんか？
      title: セキュリティ認証に失敗
```
However, I haven't see this translation anywhere. Accessing to non-existent URLs always show an error message in English.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).
