### ISSUE TITLE
Make authentication_keys translateable

### ISSUE THREAD

**Issue by m4sk1n** [tootsuite/mastodon#3977]
authentication_keys (probably now only 'Email') should be translatable. I see that it isn't…

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and ~not~ on `master`

**Comment by nightpool** [comment]
because authentication_keys uses humanized attributes, they're translatable by translating the corresponding attribute on User (in this case, email)

**Comment by nightpool** [comment]
here's an example translation for the english locale:

```yml
en:
  activerecord:
    attributes:
      user:
        email: "Email"
```
