### ISSUE TITLE
Configurable Web and Streaming Port

### ISSUE THREAD

**Issue by Moskito99** [tootsuite/mastodon#7553]
Hi!

I like the idea to configure the web and streaming port on other than 3000 and 4000.
I use a docker image and try to run more than ine instnace on a docker host.
This is not possible when all web andt streaming ports on 3000 and 4000.

Regards,
Marcus
* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Reverite** [comment]
You can change the configured listening ports and then just serve them via an Nginx reserve proxy... i.e. for Rails/Web listening on `127.0.0.1:30001` and Node/Streaming listening on `127.0.0.1:30002`:

```
  web:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    networks:
      - external_network
      - internal_network
    ports:
      - "127.0.0.1:30001:3000"
    depends_on:
      - db
      - redis
#      - es
    volumes:
      - ./public/assets:/mastodon/public/assets
      - ./public/packs:/mastodon/public/packs
      - ./public/system:/mastodon/public/system

  streaming:
    build: .
    image: tootsuite/mastodon
    restart: always
    env_file: .env.production
    command: yarn start
    networks:
      - external_network
      - internal_network
    ports:
      - "127.0.0.1:30002:4000"
    depends_on:
      - db
      - redis
```

See [Networking in Compose](https://docs.docker.com/compose/networking/) for more.
