### ISSUE TITLE
Allow resizing columns

### ISSUE THREAD

**Issue by frandavid100** [tootsuite/mastodon#8632]
My main issue with Mastodon's design is that the columns are too narrow, which makes the content look cramped and the thumbnails look too small.

Is it possible to let the user resize columns?

**Comment by Kjwon15** [comment]
Use this user-style:
```css
// Pawoo style column expand
:not(#mastodon-timeline) > .column {
  @media screen and (min-width: 631px) {
    flex: 1 0 330px;
  }
}
```
Or modify it as you want.

**Comment by black-puppydog** [comment]
This issue has come up time and again in some form or another, and rightfully so.
See: #5736, #5727, #5341, #3583, #1195, #1020, #820, #697, #499 

@Gargron closed some of those, referencing #3207, which is related (in that it does influence how space is used) but doesn't solve the problems raised *at all* since it doesn't deal with the problem (a fixed column width).

The fix @Kjwon15 suggested also comes up in many variations within those discussions. But expecting someone to install tampermonkey or such just for mastodon is a *horrible* idea and sure to slow down adoption, when the default configuration has *very* low-hanging fruit in terms of UX improvement.
So please, @Gargron, don't close this as solved, because it is really not.

**Comment by jonhoo** [comment]
Just as an aside, the rule for something like [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) would be:
```css
/* https://github.com/tootsuite/mastodon/issues/8632 */
@media screen and (min-width: 631px) {
  :not(#mastodon-timeline) > .column {
    flex: 1 0 330px;
  }
}
```

**Comment by testman42** [comment]
Any progress regarding this issue?
from what I see, it should not be that hard to implement
[Mastodon Variable Width userstyle](https://userstyles.org/styles/154943/mastodon-variable-width-variation) managed to implement it with 5 lines of CSS:
```css
div.column {
 -webkit-box-flex:1;
 -ms-flex-positive:1;
 flex-grow:1
}
```
I would be quite happy if I did not have to install this extension in every browser where I want to open Mastodon.
