### ISSUE TITLE
ERROR:  relation "accounts" does not exist

### ISSUE THREAD

**Issue by maxguru** [tootsuite/mastodon#900]
I am having difficulties using the image that is on docker hub.  Here is my setup,

```
mastodon-postgres:
  tty: true
  image: postgres:alpine
  volumes:
  - mastodon-postgres-data:/var/lib/postgresql/data
  stdin_open: true
mastodon-redis:
  tty: true
  image: redis:alpine
  volumes:
  - mastodon-redis-data:/data
  stdin_open: true
mastodon-migrations:
  environment:
    LOCAL_DOMAIN: mastodon.xxxxxxxx.xxxxxxxx
    REDIS_HOST: redis
    REDIS_PORT: '6379'
    DB_HOST: db
    DB_USER: postgres
    DB_NAME: postgres
    DB_PASS: ''
    DB_PORT: '5432'
    SINGLE_USER_MODE: 'true'
    SMTP_SERVER: mail.xxxxxxxx.xxxxxxxx
    SMTP_PORT: '587'
    SMTP_LOGIN: mastodon@xxxxxxxx.xxxxxxxx
    SMTP_PASSWORD: xxxxxxxx
    SMTP_FROM_ADDRESS: mastodon@xxxxxxxx.xxxxxxxx
    PAPERCLIP_SECRET: xxxxxxxx
    SECRET_KEY_BASE: xxxxxxxx
    OTP_SECRET: xxxxxxxx
  tty: true
  command:
  - rails
  - db:migrate
  image: gargron/mastodon
  links:
  - mastodon-postgres:db
  - mastodon-redis:redis
  volumes:
  - mastodon-assets:/mastodon/public/assets
  - mastodon-system:/mastodon/public/system
  stdin_open: true
mastodon:
  ports:
  - 18080:3000/tcp
  environment:
    LOCAL_DOMAIN: mastodon.xxxxxxxx.xxxxxxxx
    VIRTUAL_HOST: mastodon.xxxxxxxx.xxxxxxxx
    VIRTUAL_PORT: '3000'
    REDIS_HOST: redis
    REDIS_PORT: '6379'
    DB_HOST: db
    DB_USER: postgres
    DB_NAME: postgres
    DB_PASS: ''
    DB_PORT: '5432'
    SINGLE_USER_MODE: 'true'
    SMTP_SERVER: mail.xxxxxxxx.xxxxxxxx
    SMTP_PORT: '587'
    SMTP_LOGIN: mastodon@xxxxxxxx.xxxxxxxx
    SMTP_PASSWORD: xxxxxxxx
    SMTP_FROM_ADDRESS: mastodon@xxxxxxxx.xxxxxxxx
    PAPERCLIP_SECRET: xxxxxxxx
    SECRET_KEY_BASE: xxxxxxxx
    OTP_SECRET: xxxxxxxx
  domainname: xxxxxxxx.xxxxxxxx
  tty: true
  command:
  - bundle
  - exec
  - rails
  - s
  - -p
  - '3000'
  - -b
  - 0.0.0.0
  hostname: mastodon
  image: gargron/mastodon
  links:
  - mastodon-postgres:db
  - mastodon-redis:redis
  volumes:
  - mastodon-assets:/mastodon/public/assets
  - mastodon-system:/mastodon/public/system
  stdin_open: true
```

I first start `mastodon-postgres` and `mastodon-redis` containers.  Then, I run the `mastodon-migrations` container.  I get the following output,

```
4/4/2017 5:35:58 PM  [1m[35m (211.0ms)[0m  [1m[35mALTER TABLE "statuses" ALTER COLUMN "reblog_of_id" TYPE bigint[0m
4/4/2017 5:35:58 PM   -> 0.2122s
4/4/2017 5:35:58 PM-- change_column(:statuses, :in_reply_to_id, :bigint)
4/4/2017 5:35:58 PM  [1m[35m (161.4ms)[0m  [1m[35mALTER TABLE "statuses" ALTER COLUMN "in_reply_to_id" TYPE bigint[0m
4/4/2017 5:35:58 PM   -> 0.1623s
4/4/2017 5:35:58 PM-- change_column(:media_attachments, :status_id, :bigint)
4/4/2017 5:35:58 PM  [1m[35m (162.0ms)[0m  [1m[35mALTER TABLE "media_attachments" ALTER COLUMN "status_id" TYPE bigint[0m
4/4/2017 5:35:58 PM   -> 0.1657s
4/4/2017 5:35:58 PM-- change_column(:mentions, :status_id, :bigint)
4/4/2017 5:35:58 PM  [1m[35m (80.5ms)[0m  [1m[35mALTER TABLE "mentions" ALTER COLUMN "status_id" TYPE bigint[0m
4/4/2017 5:35:58 PM   -> 0.0815s
4/4/2017 5:35:58 PM-- change_column(:notifications, :activity_id, :bigint)
4/4/2017 5:35:58 PM  [1m[35m (126.9ms)[0m  [1m[35mALTER TABLE "notifications" ALTER COLUMN "activity_id" TYPE bigint[0m
4/4/2017 5:35:58 PM   -> 0.1279s
4/4/2017 5:35:58 PM-- change_column(:preview_cards, :status_id, :bigint)
4/4/2017 5:35:58 PM  [1m[35m (145.5ms)[0m  [1m[35mALTER TABLE "preview_cards" ALTER COLUMN "status_id" TYPE bigint[0m
4/4/2017 5:35:58 PM   -> 0.1464s
4/4/2017 5:35:58 PM-- change_column(:reports, :status_ids, :bigint, {:array=>true})
4/4/2017 5:35:59 PM  [1m[35m (114.3ms)[0m  [1m[35mALTER TABLE "reports" ALTER COLUMN "status_ids" TYPE bigint[][0m
4/4/2017 5:35:59 PM   -> 0.1153s
4/4/2017 5:35:59 PM-- change_column(:statuses_tags, :status_id, :bigint)
4/4/2017 5:35:59 PM  [1m[35m (82.1ms)[0m  [1m[35mALTER TABLE "statuses_tags" ALTER COLUMN "status_id" TYPE bigint[0m
4/4/2017 5:35:59 PM   -> 0.0831s
4/4/2017 5:35:59 PM-- change_column(:stream_entries, :activity_id, :bigint)
4/4/2017 5:35:59 PM  [1m[35m (140.8ms)[0m  [1m[35mALTER TABLE "stream_entries" ALTER COLUMN "activity_id" TYPE bigint[0m
4/4/2017 5:35:59 PM   -> 0.1421s
4/4/2017 5:35:59 PM== 20170322143850 ChangePrimaryKeyToBigintOnStatuses: migrated (1.4833s) ======
4/4/2017 5:35:59 PM
4/4/2017 5:35:59 PM  [1m[35mSQL (1.1ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20170322143850"]]
4/4/2017 5:35:59 PM  [1m[35m (513.6ms)[0m  [1m[35mCOMMIT[0m
4/4/2017 5:35:59 PMMigrating to AddSearchIndexToTags (20170322162804)
4/4/2017 5:35:59 PM  [1m[35m (0.7ms)[0m  [1m[35mBEGIN[0m
4/4/2017 5:35:59 PM== 20170322162804 AddSearchIndexToTags: migrating =============================
4/4/2017 5:35:59 PM-- execute("CREATE INDEX hashtag_search_index ON tags USING gin(to_tsvector('simple', tags.name));")
4/4/2017 5:35:59 PM  [1m[35m (62.2ms)[0m  [1m[35mCREATE INDEX hashtag_search_index ON tags USING gin(to_tsvector('simple', tags.name));[0m
4/4/2017 5:35:59 PM   -> 0.0631s
4/4/2017 5:35:59 PM== 20170322162804 AddSearchIndexToTags: migrated (0.0636s) ====================
4/4/2017 5:35:59 PM
4/4/2017 5:35:59 PM  [1m[35mSQL (1.0ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20170322162804"]]
4/4/2017 5:35:59 PM  [1m[35m (7.6ms)[0m  [1m[35mCOMMIT[0m
4/4/2017 5:35:59 PMMigrating to AddCounterCaches (20170330021336)
4/4/2017 5:35:59 PM  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
4/4/2017 5:35:59 PM== 20170330021336 AddCounterCaches: migrating =================================
4/4/2017 5:35:59 PM-- add_column(:statuses, :favourites_count, :integer, {:null=>false, :default=>0})
4/4/2017 5:36:00 PM  [1m[35m (201.6ms)[0m  [1m[35mALTER TABLE "statuses" ADD "favourites_count" integer DEFAULT 0 NOT NULL[0m
4/4/2017 5:36:00 PM   -> 0.2044s
4/4/2017 5:36:00 PM-- add_column(:statuses, :reblogs_count, :integer, {:null=>false, :default=>0})
4/4/2017 5:36:00 PM  [1m[35m (318.7ms)[0m  [1m[35mALTER TABLE "statuses" ADD "reblogs_count" integer DEFAULT 0 NOT NULL[0m
4/4/2017 5:36:00 PM   -> 0.3212s
4/4/2017 5:36:00 PM-- add_column(:accounts, :statuses_count, :integer, {:null=>false, :default=>0})
4/4/2017 5:36:00 PM  [1m[35m (150.4ms)[0m  [1m[35mALTER TABLE "accounts" ADD "statuses_count" integer DEFAULT 0 NOT NULL[0m
4/4/2017 5:36:00 PM   -> 0.1556s
4/4/2017 5:36:00 PM-- add_column(:accounts, :followers_count, :integer, {:null=>false, :default=>0})
4/4/2017 5:36:00 PM  [1m[35m (217.7ms)[0m  [1m[35mALTER TABLE "accounts" ADD "followers_count" integer DEFAULT 0 NOT NULL[0m
4/4/2017 5:36:00 PM   -> 0.2202s
4/4/2017 5:36:00 PM-- add_column(:accounts, :following_count, :integer, {:null=>false, :default=>0})
4/4/2017 5:36:00 PM  [1m[35m (147.2ms)[0m  [1m[35mALTER TABLE "accounts" ADD "following_count" integer DEFAULT 0 NOT NULL[0m
4/4/2017 5:36:00 PM   -> 0.1496s
4/4/2017 5:36:00 PM== 20170330021336 AddCounterCaches: migrated (1.0535s) ========================
4/4/2017 5:36:00 PM
4/4/2017 5:36:00 PM  [1m[35mSQL (4.5ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20170330021336"]]
4/4/2017 5:36:01 PM  [1m[35m (277.0ms)[0m  [1m[35mCOMMIT[0m
4/4/2017 5:36:01 PMMigrating to CreateImports (20170330163835)
4/4/2017 5:36:01 PM  [1m[35m (1.5ms)[0m  [1m[35mBEGIN[0m
4/4/2017 5:36:01 PM== 20170330163835 CreateImports: migrating ====================================
4/4/2017 5:36:01 PM-- create_table(:imports)
4/4/2017 5:36:01 PM  [1m[35m (194.3ms)[0m  [1m[35mCREATE TABLE "imports" ("id" serial primary key, "account_id" integer NOT NULL, "type" integer NOT NULL, "approved" boolean, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)[0m
4/4/2017 5:36:01 PM   -> 0.1968s
4/4/2017 5:36:01 PM== 20170330163835 CreateImports: migrated (0.1973s) ===========================
4/4/2017 5:36:01 PM
4/4/2017 5:36:01 PM  [1m[35mSQL (1.5ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20170330163835"]]
4/4/2017 5:36:01 PM  [1m[35m (22.0ms)[0m  [1m[35mCOMMIT[0m
4/4/2017 5:36:01 PMMigrating to AddAttachmentDataToImports (20170330164118)
4/4/2017 5:36:01 PM  [1m[35m (29.5ms)[0m  [1m[35mBEGIN[0m
4/4/2017 5:36:01 PM== 20170330164118 AddAttachmentDataToImports: migrating =======================
4/4/2017 5:36:01 PM-- change_table(:imports, {})
4/4/2017 5:36:01 PM  [1m[35m (33.5ms)[0m  [1m[35mALTER TABLE "imports" ADD "data_file_name" character varying[0m
4/4/2017 5:36:01 PM  [1m[35m (1.3ms)[0m  [1m[35mALTER TABLE "imports" ADD "data_content_type" character varying[0m
4/4/2017 5:36:01 PM  [1m[35m (1.0ms)[0m  [1m[35mALTER TABLE "imports" ADD "data_file_size" integer[0m
4/4/2017 5:36:01 PM  [1m[35m (1.0ms)[0m  [1m[35mALTER TABLE "imports" ADD "data_updated_at" timestamp[0m
4/4/2017 5:36:01 PM   -> 0.0423s
4/4/2017 5:36:01 PM== 20170330164118 AddAttachmentDataToImports: migrated (0.0428s) ==============
4/4/2017 5:36:01 PM
4/4/2017 5:36:01 PM  [1m[35mSQL (0.9ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20170330164118"]]
4/4/2017 5:36:01 PM  [1m[35m (30.3ms)[0m  [1m[35mCOMMIT[0m
4/4/2017 5:36:01 PMMigrating to AddActionTakenByAccountIdToReports (20170403172249)
4/4/2017 5:36:01 PM  [1m[35m (0.6ms)[0m  [1m[35mBEGIN[0m
4/4/2017 5:36:01 PM== 20170403172249 AddActionTakenByAccountIdToReports: migrating ===============
4/4/2017 5:36:01 PM-- add_column(:reports, :action_taken_by_account_id, :integer)
4/4/2017 5:36:01 PM  [1m[35m (1.2ms)[0m  [1m[35mALTER TABLE "reports" ADD "action_taken_by_account_id" integer[0m
4/4/2017 5:36:01 PM   -> 0.0023s
4/4/2017 5:36:01 PM== 20170403172249 AddActionTakenByAccountIdToReports: migrated (0.0028s) ======
4/4/2017 5:36:01 PM
4/4/2017 5:36:01 PM  [1m[35mSQL (1.0ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20170403172249"]]
4/4/2017 5:36:01 PM  [1m[35m (16.7ms)[0m  [1m[35mCOMMIT[0m
4/4/2017 5:36:01 PM  [1m[36mActiveRecord::InternalMetadata Load (2.1ms)[0m  [1m[34mSELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2[0m  [["key", :environment], ["LIMIT", 1]]
4/4/2017 5:36:01 PM  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
4/4/2017 5:36:01 PM  [1m[35mSQL (1.7ms)[0m  [1m[32mINSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "key"[0m  [["key", "environment"], ["value", "production"], ["created_at", 2017-04-05 00:36:01 UTC], ["updated_at", 2017-04-05 00:36:01 UTC]]
4/4/2017 5:36:01 PM  [1m[35m (14.7ms)[0m  [1m[35mCOMMIT[0m
4/4/2017 5:36:01 PM  [1m[35m (0.8ms)[0m  [1m[34mSELECT pg_advisory_unlock(737815420147457505)[0m
```

I then run the `mastodon` container.  Here is the log from this container,

```
4/4/2017 6:22:24 PM=> Booting Puma
4/4/2017 6:22:24 PM=> Rails 5.0.2 application starting in production on http://0.0.0.0:3000
4/4/2017 6:22:24 PM=> Run `rails server -h` for more startup options
4/4/2017 6:22:33 PMCreating scope :cache_ids. Overwriting existing method Notification.cache_ids.
4/4/2017 6:22:35 PM[1] Puma starting in cluster mode...
4/4/2017 6:22:35 PM[1] * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
4/4/2017 6:22:35 PM[1] * Min threads: 5, max threads: 5
4/4/2017 6:22:35 PM[1] * Environment: production
4/4/2017 6:22:35 PM[1] * Process workers: 2
4/4/2017 6:22:35 PM[1] * Preloading application
4/4/2017 6:22:35 PM[1] * Listening on tcp://0.0.0.0:3000
4/4/2017 6:22:35 PM[1] Use Ctrl-C to stop
4/4/2017 6:22:35 PM[1] - Worker 0 (pid: 14) booted, phase: 0
4/4/2017 6:22:35 PM[1] - Worker 1 (pid: 24) booted, phase: 0
4/4/2017 6:23:39 PM[59dedcbb-d8d9-4914-a7ad-6916dc6a9a9e]   [1m[36mAccount Load (3.1ms)[0m  [1m[34mSELECT  "accounts".* FROM "accounts" ORDER BY "accounts"."id" ASC LIMIT $1[0m  [["LIMIT", 1]]
4/4/2017 6:23:39 PM[59dedcbb-d8d9-4914-a7ad-6916dc6a9a9e] method=GET path=/ format=html controller=HomeController action=index status=500 error='ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "accounts" does not exist
4/4/2017 6:23:39 PMLINE 1: SELECT  "accounts".* FROM "accounts" ORDER BY "accounts"."id...
4/4/2017 6:23:39 PM                                  ^
4/4/2017 6:23:39 PM: SELECT  "accounts".* FROM "accounts" ORDER BY "accounts"."id" ASC LIMIT $1' duration=189.73 view=0.00 db=31.89
4/4/2017 6:23:39 PM[59dedcbb-d8d9-4914-a7ad-6916dc6a9a9e]   
4/4/2017 6:23:39 PM[59dedcbb-d8d9-4914-a7ad-6916dc6a9a9e] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "accounts" does not exist
4/4/2017 6:23:39 PMLINE 1: SELECT  "accounts".* FROM "accounts" ORDER BY "accounts"."id...
4/4/2017 6:23:39 PM                                  ^
4/4/2017 6:23:39 PM: SELECT  "accounts".* FROM "accounts" ORDER BY "accounts"."id" ASC LIMIT $1):
4/4/2017 6:23:39 PM[59dedcbb-d8d9-4914-a7ad-6916dc6a9a9e]   
4/4/2017 6:23:39 PM[59dedcbb-d8d9-4914-a7ad-6916dc6a9a9e] app/controllers/home_controller.rb:15:in `authenticate_user!'
```

I get the 'We're sorry, but something went wrong.' screen when I try to access the web UI.
